name: Deploy

concurrency: production

# Manual workflow
on: workflow_dispatch

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

      # Merge main into the production branch to synchronize production, and trigger the deployment
      # WARN: We don't just try to merge the PR like we do with releases because it breaks the commit history
      # References:
      # https://stackoverflow.com/questions/60597400/how-to-do-a-fast-forward-merge-on-github
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          gh pr create --title "Deploy ${GITHUB_SHA}" --body "This is a Deployment PR" --base production --head main
          git switch main
          git pull
          git switch production
          git rebase origin/main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NX_NO_CLOUD: true
